"""Star-schema migration for the classification layer.

Dimensions
    projects   — one row per dataset (cleaned of old-notebook classification cruft)
    files      — one row per file
    dim_isic   — ISIC Rev. 5 reference: class ("N/72") -> section/division + titles

Fact
    classifications — one row per classified entity (PROJECT or FILE), keyed by
    ``entity_type``. Holds only measures + the ``class`` join key; section /
    division titles live in dim_isic, not here.

The migration is idempotent: it drops leftover columns, (re)builds the ISIC
dimension, and consolidates the old two-table classification design into the
single fact table. Existing classification rows are disposable (regenerated by
the next pipeline run), so the old tables are dropped rather than migrated.
"""
import logging
import sqlite3

from classify.taxonomy import dim_isic_rows

log = logging.getLogger("classify.schema")

# Old-notebook / superseded columns to strip from the dimension tables.
_PROJECTS_DROP = ["project_type", "isic_section", "isic_division",
                  "isic_tags", "confidence", "secondary_class"]
_FILES_DROP = ["isic_section", "isic_division"]

# Convenience label columns kept denormalised on the dimensions.
_PROJECTS_KEEP_ADD = {"type": "TEXT", "class": "TEXT"}
_FILES_KEEP_ADD = {"class": "TEXT"}

_CREATE_DIM_ISIC = """
CREATE TABLE IF NOT EXISTS dim_isic (
    class          TEXT PRIMARY KEY,   -- 'N/72'
    isic_section   TEXT NOT NULL,
    isic_division  TEXT NOT NULL,
    section_title  TEXT NOT NULL,
    division_title TEXT NOT NULL
)
"""

_CREATE_CLASSIFICATIONS = """
CREATE TABLE IF NOT EXISTS classifications (
    id                    INTEGER PRIMARY KEY AUTOINCREMENT,
    entity_type           TEXT NOT NULL CHECK (entity_type IN ('PROJECT', 'FILE')),
    project_id            INTEGER NOT NULL,
    file_id               INTEGER,          -- NULL for PROJECT rows
    repository            TEXT,             -- zenodo | figshare | dryad
    class                 TEXT,             -- 'N/72', joins dim_isic
    isic_section          TEXT,
    isic_division         TEXT,
    section_confidence    REAL,
    division_confidence   REAL,
    classification_status TEXT NOT NULL
        CHECK (classification_status IN (
            'ACCEPTED', 'NEEDS_REVIEW', 'AMBIGUOUS',
            'INSUFFICIENT_DATA', 'NO_TEXT', 'ERROR'
        )),
    secondary_class       TEXT,
    secondary_section     TEXT,
    secondary_division    TEXT,
    method                TEXT,             -- cosine | rerank
    rerank_confidence     REAL,
    summary               TEXT,             -- PROJECT rows only
    flags                 TEXT,
    classified_at         TIMESTAMP NOT NULL DEFAULT (datetime('now','utc')),
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY (file_id) REFERENCES files(id) ON DELETE CASCADE
)
"""
# One classification per project and per file (partial unique indexes because
# file_id is NULL on PROJECT rows).
_INDEX_PROJECT = (
    "CREATE UNIQUE INDEX IF NOT EXISTS ux_class_project "
    "ON classifications(project_id) WHERE entity_type='PROJECT'"
)
_INDEX_FILE = (
    "CREATE UNIQUE INDEX IF NOT EXISTS ux_class_file "
    "ON classifications(file_id) WHERE entity_type='FILE'"
)


def _column_exists(conn: sqlite3.Connection, table: str, column: str) -> bool:
    rows = conn.execute(f"PRAGMA table_info({table})").fetchall()
    return any(row[1] == column for row in rows)


def _tables(conn: sqlite3.Connection) -> set[str]:
    return {r[0] for r in conn.execute(
        "SELECT name FROM sqlite_master WHERE type='table'").fetchall()}


def populate_dim_isic(conn: sqlite3.Connection) -> int:
    rows = dim_isic_rows()
    conn.executemany(
        "INSERT OR REPLACE INTO dim_isic "
        "(class, isic_section, isic_division, section_title, division_title) "
        "VALUES (?,?,?,?,?)",
        rows,
    )
    return len(rows)


def migrate(db_path: str, dry_run: bool = False) -> list[str]:
    ops: list[str] = []

    with sqlite3.connect(db_path) as conn:
        # 1. Ensure the kept convenience columns exist on the dimensions.
        for col, coltype in _PROJECTS_KEEP_ADD.items():
            if not _column_exists(conn, "projects", col):
                ops.append(f"ALTER TABLE projects ADD COLUMN {col} {coltype}")
                if not dry_run:
                    conn.execute(f"ALTER TABLE projects ADD COLUMN {col} {coltype}")
        for col, coltype in _FILES_KEEP_ADD.items():
            if not _column_exists(conn, "files", col):
                ops.append(f"ALTER TABLE files ADD COLUMN {col} {coltype}")
                if not dry_run:
                    conn.execute(f"ALTER TABLE files ADD COLUMN {col} {coltype}")

        # 2. Strip old-notebook classification cruft from the dimensions.
        for col in _PROJECTS_DROP:
            if _column_exists(conn, "projects", col):
                ops.append(f"ALTER TABLE projects DROP COLUMN {col}")
                if not dry_run:
                    conn.execute(f"ALTER TABLE projects DROP COLUMN {col}")
                    log.info("Dropped projects.%s", col)
        for col in _FILES_DROP:
            if _column_exists(conn, "files", col):
                ops.append(f"ALTER TABLE files DROP COLUMN {col}")
                if not dry_run:
                    conn.execute(f"ALTER TABLE files DROP COLUMN {col}")
                    log.info("Dropped files.%s", col)

        existing = _tables(conn)

        # 3. ISIC dimension.
        if "dim_isic" not in existing:
            ops.append("CREATE TABLE dim_isic")
            if not dry_run:
                conn.execute(_CREATE_DIM_ISIC)
                n = populate_dim_isic(conn)
                log.info("Created and populated dim_isic (%d rows)", n)
        elif not dry_run:
            # Keep reference data in sync with taxonomy.py.
            populate_dim_isic(conn)

        # 4. Consolidate to the single merged fact table. Old classification
        #    rows are disposable, so replace the old design outright.
        merged = "classifications" in existing and _column_exists(
            conn, "classifications", "entity_type")
        if not merged:
            ops.append("REBUILD classifications (merged fact)")
            if not dry_run:
                conn.execute("DROP TABLE IF EXISTS file_classifications")
                conn.execute("DROP TABLE IF EXISTS classifications")
                conn.execute(_CREATE_CLASSIFICATIONS)
                conn.execute(_INDEX_PROJECT)
                conn.execute(_INDEX_FILE)
                log.info("Rebuilt classifications as merged fact table")

        if not dry_run:
            conn.commit()

    if dry_run:
        log.info("Dry run — would apply: %s", ops)
    elif not ops:
        log.debug("Schema already up to date, nothing to do")

    return ops
